Vagrant.configure("2") do |config|
         config.vm.provider :libvirt do |libvirt|
         config.vm.network "private_network", ip: "192.168.122.4"
         libvirt.driver = "kvm"
         libvirt.host = 'localhost'
         libvirt.uri = 'qemu:///system'
         libvirt.nested = true
         end
config.vm.define "new" do |custombox|
         custombox.vm.box = "custombox"       
         custombox.vm.provider :libvirt do |test|
         test.memory = 1024
         test.cpus = 1
         end
         end
end
